//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaGlobal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.61.28:50001/b1s/v1/")]
        public string SL {
            get {
                return ((string)(this["SL"]));
            }
            set {
                this["SL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST_DERMA")]
        public string CompanyDB {
            get {
                return ((string)(this["CompanyDB"]));
            }
            set {
                this["CompanyDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("manager")]
        public string UserSAP {
            get {
                return ((string)(this["UserSAP"]));
            }
            set {
                this["UserSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B1AdminH2")]
        public string PassSAP {
            get {
                return ((string)(this["PassSAP"]));
            }
            set {
                this["PassSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string Frecuencia {
            get {
                return ((string)(this["Frecuencia"]));
            }
            set {
                this["Frecuencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=172.16.61.28:30013;UserID=SYSTEM;Password=B1AdminH2;Database=NDB")]
        public string HanaConection {
            get {
                return ((string)(this["HanaConection"]));
            }
            set {
                this["HanaConection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string UN {
            get {
                return ((string)(this["UN"]));
            }
            set {
                this["UN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101476")]
        public string CardCode {
            get {
                return ((string)(this["CardCode"]));
            }
            set {
                this["CardCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VENTA")]
        public string ItemCode {
            get {
                return ((string)(this["ItemCode"]));
            }
            set {
                this["ItemCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XAXX010101000")]
        public string Rfc {
            get {
                return ((string)(this["Rfc"]));
            }
            set {
                this["Rfc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public string Serie {
            get {
                return ((string)(this["Serie"]));
            }
            set {
                this["Serie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S01")]
        public string UsoCFDI {
            get {
                return ((string)(this["UsoCFDI"]));
            }
            set {
                this["UsoCFDI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PUE")]
        public string MetodoPago {
            get {
                return ((string)(this["MetodoPago"]));
            }
            set {
                this["MetodoPago"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02")]
        public string Periodicidad {
            get {
                return ((string)(this["Periodicidad"]));
            }
            set {
                this["Periodicidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>01-EF-A</string>
  <string>01-EF-C</string>
  <string>01-EF-D</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Efectivo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Efectivo"]));
            }
            set {
                this["Efectivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>04-TC-A</string>\r\n  <string>04-TC-C</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TC {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TC"]));
            }
            set {
                this["TC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>28-TD-A</string>\r\n  <string>28-TD-C</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TD"]));
            }
            set {
                this["TD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>03-C</string>
  <string>03-KK-A</string>
  <string>03-KK-D</string>
  <string>03-MP-A</string>
  <string>03-MP-D</string>
  <string>03-OP-A</string>
  <string>03-OP-D</string>
  <string>03-PP-A</string>
  <string>03-PP-D</string>
  <string>03-TR-A</string>
  <string>03-TR-C</string>
  <string>03-TR-D</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Transferencia {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Transferencia"]));
            }
            set {
                this["Transferencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string SerieE {
            get {
                return ((string)(this["SerieE"]));
            }
            set {
                this["SerieE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string SerieC {
            get {
                return ((string)(this["SerieC"]));
            }
            set {
                this["SerieC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string SerieD {
            get {
                return ((string)(this["SerieD"]));
            }
            set {
                this["SerieD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uno")]
        public string PeyMethodA {
            get {
                return ((string)(this["PeyMethodA"]));
            }
            set {
                this["PeyMethodA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dos")]
        public string PeyMethodD {
            get {
                return ((string)(this["PeyMethodD"]));
            }
            set {
                this["PeyMethodD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tres")]
        public string PeyMethodC {
            get {
                return ((string)(this["PeyMethodC"]));
            }
            set {
                this["PeyMethodC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GroupNum")]
        public string GroupNum {
            get {
                return ((string)(this["GroupNum"]));
            }
            set {
                this["GroupNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>PG001</string>\r\n  <string>PG002</string>\r\n  <string>PG003</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection PublicoGeneral {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PublicoGeneral"]));
            }
            set {
                this["PublicoGeneral"] = value;
            }
        }
    }
}
